#!/usr/bin/env bash
set -euo pipefail

# build.sh — bundle pwgen-bash.sh and wordlists into a single self-contained executable
# Usage:
#   ./build.sh [OUTPUT_FILE]
#
# If OUTPUT_FILE is omitted, defaults to ./pwgen-bash in this directory.
#
# The generated single-file executable embeds the wordlists and, at runtime,
# extracts them to a temporary directory and runs the bundled pwgen-bash.sh script
# with PWGEN_WORDLISTS_DIR pointing to that directory. No external files are required.

this_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
src_script="$this_dir/pwgen-bash.sh"
wordlist_dir="$this_dir/wordlists"
output_path="$this_dir/pwgen-bash"

if [[ ! -f "$src_script" ]]; then
  echo "ERROR: Cannot find source script: $src_script" >&2
  exit 1
fi
if [[ ! -d "$wordlist_dir" ]]; then
  echo "ERROR: Cannot find wordlists directory: $wordlist_dir" >&2
  exit 1
fi
shopt -s nullglob
wordlists=("$wordlist_dir"/wordlist_*.txt)
shopt -u nullglob
if (( ${#wordlists[@]} == 0 )); then
  echo "ERROR: No wordlist_*.txt files found in $wordlist_dir" >&2
  exit 1
fi

# Start writing the standalone script
: > "$output_path"
chmod 0644 "$output_path"

{
  cat <<'BOOTSTRAP'
#!/usr/bin/env bash
set -euo pipefail
# Autogenerated by pwgen-bash/build.sh — single-file standalone script
# This file embeds the wordlists and the pwgen-bash logic.

# Create a temporary directory for embedded assets
TMPDIR_STANDALONE="$(mktemp -d)"
cleanup() {
  # Best-effort cleanup
  rm -rf -- "$TMPDIR_STANDALONE" || true
}
trap cleanup EXIT INT TERM

# Write embedded wordlists
BOOTSTRAP

  # Embed each wordlist as a literal heredoc
  for wl in "${wordlists[@]}"; do
    base="$(basename -- "$wl")"
    # Use a unique heredoc tag per file to avoid accidental conflicts
    tag="WL_EOF_${base//[^A-Za-z0-9_]/_}"
    echo "cat >\"\$TMPDIR_STANDALONE/$base\" <<'$tag'"
    cat "$wl"
    echo "$tag"
    echo
  done

  cat <<'POST_WORDLISTS'
# Point the pwgen script to the embedded wordlists
export PWGEN_WORDLISTS_DIR="$TMPDIR_STANDALONE"

# ----- Begin embedded pwgen-bash script -----
POST_WORDLISTS

  # Append the pwgen-bash.sh script, without its initial shebang line
  tail -n +2 "$src_script"

  cat <<'END_SCRIPT'
# ----- End embedded pwgen-bash script -----
END_SCRIPT
} >> "$output_path"

chmod +x "$output_path"

echo "Standalone script created: $output_path"
