# Include wordlist resources and logback.xml in the native image
quarkus.native.additional-build-args=-H:+UnlockExperimentalVMOptions,-H:IncludeResources=wordlist_.*.txt

# Make quarkus less verbose
quarkus.log.level=WARN
quarkus.log.console.enable=false
