# This is a basic workflow that is manually triggered

name: Build packages

on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Alternatives: 'zulu', 'oracle', 'corretto', etc.
          java-version: '21'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build all artifacts
        run: ./build.sh
