# This is a basic workflow that is manually triggered

name: Build packages

on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Build all artifacts
      run: ./build.sh
