# This is a basic workflow that is manually triggered

name: Build packages

on:
  release:
    types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Alternatives: 'zulu', 'oracle', 'corretto', etc.
          java-version: '21'

      - name: Build all artifacts
        run: ./build.sh
